name: CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  repository_dispatch:
    types: [trigger-build]

  workflow_dispatch:

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build App
      run: make build-all

    - name: Test App
      run: make test-all

  